/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Genzee } from "./Genzee";
export type { GoldenPass } from "./GoldenPass";
export type { Oddworx } from "./Oddworx";
export type { OddworxStaking } from "./OddworxStaking";
export * as factories from "./factories";
export { Genzee__factory } from "./factories/Genzee__factory";
export { Oddworx__factory } from "./factories/Oddworx__factory";
export { OddworxStaking__factory } from "./factories/OddworxStaking__factory";
export { GoldenPass__factory } from "./factories/GoldenPass__factory";
