/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { GoldenPass } from "./GoldenPass";
export * as factories from "./factories";
export { GoldenPass__factory } from "./factories/GoldenPass__factory";
